### ISSUE TITLE
Safer default value for ServerFactory.maxThreads

### ISSUE THREAD

**Issue by stariy95** [bootique/bootique-jetty#95]
Our current default value for max threads (1024) could lead to memory problems in high-loaded setups.
We should think about lowering this to be safer for unaware users. Jetty [documentation](https://www.eclipse.org/jetty/documentation/current/high-load.html#_thread_pool) suggests typical value between 50 and 500. The default value in Jetty itself is 200, so I suggest we go with this too.

**Comment by andrus** [comment]
I am +1 on 200. The usual approach to integration with Bootique is to keep the defaults from the integrated framework unchanged.
